name: My First Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'GitHub User'
        type: string
      age:
        description: 'Your age'
        required: false
        default: '25'
        type: number
      ismarried:
        description: 'Are you married?'
        required: false
        default: true
        type: boolean
      selection:
        description: 'Choose an option'
        required: true
        default: 'option1'
        type: choice
        options:
          - option1
          - option2
          - option3
      

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World Welcome to GitHub Actions"
    
      - name: Display Inputs
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Age: ${{ github.event.inputs.age }}"
          echo "Is Married: ${{ github.event.inputs.ismarried }}"
          echo "Selection: ${{ github.event.inputs.selection }}"