name: second

on:
    workflow_run:
        workflows: ["first"]
        types:
            - completed

jobs:
    SecondJob:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World from Second Workflow triggered by First Workflow"
            - name: Display First Workflow Inputs
              run: |
                echo "Username from First Workflow: ${{ github.event.workflow_run.inputs.username }}"
                echo "Password from First Workflow: ${{ github.event.workflow_run.inputs.password }}"
